# Generated by Django 3.2.7 on 2021-11-06 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ac_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
