# Generated by Django 3.2.7 on 2021-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_payment_ac_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivary',
            field=models.BooleanField(default=False),
        ),
    ]
