# Generated by Django 3.2.7 on 2021-11-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
